name: Workflow to test reusable.yaml

on:
  workflow_dispatch: 

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: test reusable file
        uses: ./.github/workflows/reusable.yaml
        with:
          username: Rose
  
